runtime: nodejs
env: flex

# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  SQL_USER: root
  SQL_PASSWORD: [PASSWORD]
  SQL_DATABASE: btr
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: betherichest-1994:europe-west1:btrsql
  MONGO_NAME: btr
  MONGO_PW: [PASSWORD]
